services:
  webui:
    build:
      context: ./webui
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - DEBUG=vite:*
    container_name: autheo-devhub-webui
    restart: always
    ports:
      - "80:80"  # Changed from 8000:80 as requested
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - autheo-devhub
      
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: autheo-devhub-mattermost
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database settings
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://postgres:autheo_secure_pass@postgres:5432/mattermost?sslmode=disable
      
      # Server settings
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8085
      - MM_SERVICESETTINGS_LISTENADDRESS=:8000
      
      # File storage settings
      - MM_FILESETTINGS_DRIVERNAME=local
      - MM_FILESETTINGS_DIRECTORY=/mattermost/data
      
      # Log settings
      - MM_LOGSETTINGS_ENABLECONSOLE=true
      - MM_LOGSETTINGS_CONSOLELEVEL=INFO
      - MM_LOGSETTINGS_ENABLEFILE=true
      - MM_LOGSETTINGS_FILELEVEL=INFO
      - MM_LOGSETTINGS_FILEFORMAT=json
      
      # Plugin settings
      - MM_PLUGINSETTINGS_ENABLE=true
      - MM_PLUGINSETTINGS_DIRECTORY=/mattermost/plugins
      - MM_PLUGINSETTINGS_CLIENTDIRECTORY=/mattermost/client/plugins
    ports:
      - "8085:8000"
    volumes:
      - mattermost-data:/mattermost/data
      - mattermost-logs:/mattermost/logs
      - mattermost-config:/mattermost/config
      - mattermost-plugins:/mattermost/plugins
      - mattermost-client-plugins:/mattermost/client/plugins
    networks:
      - autheo-devhub

  postgres:
    image: postgres:14
    container_name: autheo-devhub-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=autheo_secure_pass
      - POSTGRES_MULTIPLE_DATABASES=gitea,openproject,n8n,mattermost
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - autheo-devhub

  openproject:
    image: openproject/openproject:15.3.0
    container_name: autheo-devhub-openproject
    environment:
      - DATABASE_URL=postgres://openproject:openproject@postgres:5432/openproject
      - RAILS_CACHE_STORE=memcache
      - RAILS_CACHE_STORE_URL=memcached:11211
      - RAILS_MIN_THREADS=4
      - RAILS_MAX_THREADS=16
      - RAILS_SERVE_STATIC_FILES=true
      - OPENPROJECT_HTTPS=false
      - OPENPROJECT_HOST__NAME=localhost:8081
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - autheo-devhub

  memcached:
    image: memcached:1.6
    container_name: autheo-devhub-memcached
    command: ["-m", "64"]
    healthcheck:
      test: ["CMD-SHELL", "echo stats | nc localhost 11211"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - autheo-devhub

  gitea:
    build:
      context: ./gitea/github
      dockerfile: Dockerfile
      args:
        - TAGS=sqlite sqlite_unlock_notify
    container_name: autheo-devhub-gitea
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__ui__DEFAULT_THEME=gitea
      - GITEA__ui__THEMES=gitea,arc-green,custom
      - GITEA__server__LANDING_PAGE=explore
    volumes:
      - gitea_data:/data
      - ./gitea/frontend/dist:/data/gitea/public/custom
      - ./gitea/frontend/templates:/data/gitea/templates/custom
    ports:
      - "8082:3000"
      - "2222:22"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - autheo-devhub
    restart: always

  n8n:
    image: n8nio/n8n:latest
    container_name: autheo-devhub-n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - N8N_HOST=localhost
      - N8N_PORT=8083
      - N8N_PROTOCOL=http
      - N8N_USER_MANAGEMENT_DISABLED=false
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_SECURE_COOKIE=false
      - N8N_ENCRYPTION_KEY=a-random-32-character-string-here
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:8083/
      - GENERIC_TIMEZONE=America/Denver
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - N8N_SMTP_PORT=${SMTP_PORT:-587}
      - N8N_SMTP_USER=${SMTP_USER:-your-email@example.com}
      - N8N_SMTP_PASS=${SMTP_PASSWORD:-your-smtp-password}
      - N8N_SMTP_SENDER=${SMTP_SENDER:-your-email@example.com}
    ports:
      - "8083:8083"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - autheo-devhub

volumes:
  postgres_data:
    name: autheo-devhub-postgres-data
  gitea_data:
    name: autheo-devhub-gitea-data
  n8n_data:
    name: autheo-devhub-n8n-data
  mattermost-data:
    name: autheo-devhub-mattermost-data
  mattermost-logs:
    name: autheo-devhub-mattermost-logs
  mattermost-config:
    name: autheo-devhub-mattermost-config
  mattermost-plugins:
    name: autheo-devhub-mattermost-plugins
  mattermost-client-plugins:
    name: autheo-devhub-mattermost-client-plugins

networks:
  autheo-devhub:
    name: autheo-devhub-network
    driver: bridge